CREATE TABLE IF NOT EXISTS LOGS(login VARCHAR(20) PRIMARY KEY , pass VARCHAR(12));
CREATE TABLE IF NOT EXISTS GAME(gameid VARCHAR(20) PRIMARY KEY,title VARCHAR(50), publisher VARCHAR(30),available VARCHAR(3));
CREATE TABLE IF NOT EXISTS MEMBERS(memberid VARCHAR(20) PRIMARY KEY, firstname VARCHAR(30), lastname VARCHAR(30));
CREATE TABLE IF NOT EXISTS BORROW( gameid VARCHAR(20) PRIMARY KEY , memberid VARCHAR(20), due_date DATE, borrow_date DATE, return_date DATE)